### ISSUE TITLE
关于您提到的1，2，3，跟CWRU数据集中的低负载，中负载，高负载L,M,H的关系又是什么？一一对应吗？如果不是，那么又是什么关系呢？

### ISSUE THREAD

**Issue by ZUEL-hyzhang** [Yifei20/Few-shot-Fault-Diagnosis-MAML#2]
希望您能解释一下，如果不是对应关系，怎么设置所谓的L->M, L->H的域迁移呢？
诚恳希望您的解答！

**Comment by yeefaydu** [comment]
你好，据我所知 CWRU 数据集采用的是数字0到3标注负载情况（即 0 to 3 horsepower），我文中提到的数字1,2,3与 CWRU 数据集官方标注相同。你提到的低中高负载的标注方式应该对应 1-3 马力，是一一对应关系，具体请参考 [CWRU 数据集官网](https://engineering.case.edu/bearingdatacenter/welcome)。

此外，本文中的实验设定有两种情况，一种是“多工况迁移”，即从除目标工况外的多种工况迁移到目标工况（如工况0,1,2迁移到工况3）这在实验结果里标注为`MDML`；另一种是“单工况迁移”，即为一种工况向另一种工况的迁移（如工况1迁移到工况3），这种情况下实验结果为除目标工况外其余所有工况作为源工况迁移的平均值（如 0-3, 1-3, 2-3 三个实验结果的平均值），在实验结果中标注为`MAML`。

如果你需要调用单工况迁移，你只需要在 `train_domains` 这一栏简单指明你需要的训练工况，如下示代码即表示“L->H”的域迁移

```
python train_maml.py --train_domains 1 --test_domain 3
```

希望这个回答能帮到你。

**Comment by ZUEL-hyzhang** [comment]
感谢您的回答，对我帮助很大！
